### ISSUE TITLE
Possibility of prioritizing workflow instances?

### ISSUE THREAD

**Issue by ptorkko** [NitorCreations/nflow#284]
We are currently "abusing" nflow for some data import batch processing by splitting the work into several hundred child workflows that the cluster can then execute in parallel. The same cluster is also responsible for some higher priority work like sending emails.

Problem here is that if the batch processing takes e.g. 30 minutes total, nothing else will be executed in that time due to how `next_activation` is prioritized.

I've hacked around this with:

    // schedule incrementally in the future, so execution won't lag badly
    .setNextActivation(now.plusMillis(1000 * increment.getAndIncrement()))

, but some native way of prioritizing workflows relative to each other would be nice. In this case it would be enough to say "only execute this workflow when there's nothing else to execute", so that an email workflow with a later next_activation  still gets executed before these batch workflows.

Willing to work on a PR if you outline something, and at least Esa Puttonen is familiar with the usecase.

**Comment by gmokki** [comment]
After pondering the prioritization of workflows and the use case you presented we came to conclusion that adding a priority field to the nFlow core is not the optimal solution.
Instead you get better results by tuning the parent&child workflow code. Here is how:
1. You should create all the child workflows with `next_activation=null`
2. You should add `execution.wakeUpParentWorkflow()` to all child workflow end states
3. Code the parent workflow so that when it wakes it loops through the states of child workflows and if less than wanted number are running it wakes more up with `WorkflowInstanceService.wakeupWorkflowInstance`

This solution is better than priority because
- it will not block other workflows of the same priority
- even if there are a lot of bulk workflows with thousands of children for each the system always makes progress forward for all without too much blocking

Further improvements:
- you can tune the parent workflow to progress at different speed during day time and night time
- you can make the concurrency configurable and can then control it via UI to speed up / slow down large bulks

I have used the above strategy with bulks that contain up-to 50k children, with many such bulks running at the same time while also having more interactive operations pass through the system without any significant delay.

To get you started I created a sample parent workflow that does the wakeups: https://github.com/NitorCreations/nflow/commit/6f6eb6983b0b0946fad30f9673d4ab0799aafd62
We will likely add it to some later nFlow release.

**Comment by ptorkko** [comment]
Thanks for the example, refactored the workflow to use this pattern and it works nicely.

Some questions:
* example uses retry instead of moveToStateAfter, is there a specific reason?
* is there a simple way to throttle the "wake up rate" of the parent? even if to just to reduce the amount of state changes to avoid polluting the views in explorer

**Comment by jsyrjala** [comment]
`retryAfter` does the same thing as `moveToStateAfter` that targets the current state. It is just a shorthand and a more explicit way to retry again the same state.

**Comment by jsyrjala** [comment]
Release [5.4.1](https://github.com/NitorCreations/nflow/releases/tag/5.4.1) contains the BulkWorkflow that you can extend.
