### ISSUE TITLE
Running a workflow instance as a recurring job

### ISSUE THREAD

**Issue by steowens** [NitorCreations/nflow#476]
I have developed a workflow which periodically executes a single action by ending the action with

`
return NextAction.retryAfter(dateTime, "Processing timer event"); 
`
Where dateTime is something on the order of 5 to 15 minutes in the future with respect to the time the statement is executed.

At any rate, I launch the workflow in the @PostConstruct method of one of our rest controllers as so:

`
workflowInstances.insertWorkflowInstance(
				workflowInstanceFactory.newWorkflowInstanceBuilder().setType(TimerWorkflow.TYPE)
						.setExternalId("TIMER_MODULE")
						.build());
`

At any rate the first time I ran this in an environment it worked just fine.  But when I re-deployed the container and it started up again, I got this error:

00:11:41.316 WARN [main] io.nflow.engine.internal.dao.WorkflowInstanceDao [WorkflowInstanceDao.java : 200] - Failed to insert workflow instance
org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [with wf as (insert into nflow_workflow(type, priority, parent_workflow_id, parent_action_id, business_key, external_id, executor_group, status, state, state_text, next_activation, workflow_signal) values (?, ?, ?, ?, ?, ?, ?, ?::workflow_status, ?, ?, ?, ?) returning id) select wf.id from wf]; ERROR: duplicate key value violates unique constraint "nflow_workflow_uniq"
  Detail: Key (external_id, type, executor_group)=(TIMER_MODULE, timerWorkflow, nflow) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "nflow_workflow_uniq"
  Detail: Key (external_id, type, executor_group)=(TIMER_MODULE, timerWorkflow, nflow) already exists.

I presume this is because the external Id is hard coded.   So the question is, what is the right way to launch a repeating workflow that continues to execute indefinitely in an environment where the executors may be containers which are by their very nature ephemeral.  What should the workflow startup login actually look like?

Also is there any issue with letting a single workflow instance run forever waking periodically to execute sundry housekeeping tasks?

**Comment by efonsell** [comment]
I would recommend you to have a look at `io.nflow.engine.workflow.curated.CronWorkflow` for implementing a periodically running workflow. Have a look at `io.nflow.engine.workflow.curated.MaintenanceWorkflow` to see an example.

To avoid logging that warning when inserting the workflow, just check if the instance already exists before inserting a new instance in your @PostConstruct method. For example, see https://github.com/NitorCreations/nflow/blob/891c719d17f2598c93d7f85968f217fc04484f10/nflow-engine/src/main/java/io/nflow/engine/internal/workflow/MaintenanceWorkflowStarter.java#L57

For long (or forever) running workflows, it is recommended to enable the workflow state and history cleanup. For more details, see https://github.com/NitorCreations/nflow/blob/891c719d17f2598c93d7f85968f217fc04484f10/nflow-engine/src/main/java/io/nflow/engine/workflow/definition/WorkflowSettings.java#L239

**Comment by steowens** [comment]
Thanks one question, is there any limit on how long such a workflow can run.  I presume we get some entries for each time the workflow wakes up and does it's maintenance task.  What happens if the same workflow runs long enough to wake up a billion times?

**Comment by efonsell** [comment]
AFAIK there is no limit for how long workflows can run.

Every time a workflow instance state is processed, there are new entries created to nFlow database for the action and for the state variables that were modified. The maximum number of recorded actions is 9,223,372,036,854,775,807 (`Long.MAX_VALUE`), but that is a pretty huge number, and if you want, you can avoid creating actions by calling `StateExecution.setCreateAction(false)` in your long running workflow's state method. Additionally, it is recommended to enable workflow instance history cleanup (as I suggested before), otherwise the nFlow database tables for actions and state variables can grow huge and eventually impact the performance. But with workflow instance history cleanup enabled, there should be no problems.

Of course there is also some logging done by nFlow via slf4j, but if you have configured log level and rotation properly like in any long running system, that should not be a problem either.

So, if you have the history cleanup enabled, the same workflow will keep running smoothly after waking up billion times, and the next billion times as well.

**Comment by steowens** [comment]
Thank you this is most helpful!
