### ISSUE TITLE
org.hibernate.LazyInitializationException: could not initialize proxy - no Session

### ISSUE THREAD

**Issue by infraorder** [NitorCreations/nflow#508]
I have an NflowWorkflow that looks similar to this:
```
@Component
public class CustomerCreationWorkflow extends WorkflowDefinition<CustomerCreationWorkflow.State> {

	protected final fooRemoteService fooRemoteService;
	
	public CustomerCreationWorkflow(FooRemoteService fooRemoteService) {
			super(TYPE, State.createCustomer, State.done);
			this.fooRemoteService = fooRemoteService;
	}
	
	// STATE ETC
	
	public NextAction createCustomer(StateExecution execution,
	                                 @StateVar(value = REQUEST_DATA, readOnly = true) CustomerEnrollmentState request) {
		fooRemoteService.get(request.something)
	}
}
```
Which is leading to `org.hibernate.lazyinitializationexception could not initialize proxy no session`
Is there a way of using spring jpa inside an nflow workflow?
Or is that even possible?

What is the preferred way of doing something like this?

Sorry for bombarding your issue logs.
Is there a better place to put these?

**Comment by efonsell** [comment]
I'm not sure if it is necessary to have `@Inject` annotation in the constructor. Anyway, if that doesn't work, you could try using field injection, i.e. remove the `FooRemoteService` parameter from the constructor and add `@Inject` annotation to the field. At least that has worked for me.

Don't worry about bombarding our issue log, there will be no civil casualties caused by it. This is the preferred place where we like to get the issues.

**Comment by infraorder** [comment]
Using `@Autowired` or `@Inject` give same result

**Comment by efonsell** [comment]
Same result with constructor and field injection as well?

**Comment by infraorder** [comment]
Solved by adding:
`registry.addMapping("/vsuite/vgateway/enrollment/nflow/**");` to jpa properties
and adding `@Transactional` on my workflow
